In [1]:
import qiskit
from qiskit import QuantumCircuit, QuantumRegister, execute, BasicAer, ClassicalRegister, IBMQ
from qiskit.compiler import transpile

In [2]:
qasm = """\
OPENQASM 2.0;
include "qelib1.inc";
qreg q[3];
ry(1.42959172294254) q[0];
ry(2.89888708742281) q[1];
cx q[0],q[1];
ry(1.09639370892771) q[0];
ry(-0.930163527890557) q[1];
ry(1.47262155637022) q[2];
cx q[0],q[2];
ry(-0.0981747704246810) q[2];
cx q[1],q[2];
ry(0.0981747704246810) q[2];
cx q[0],q[2];
ry(-0.294524311274043) q[2];
cx q[1],q[2];\
"""
qc = QuantumCircuit.from_qasm_str(qasm)

qasm += """\
creg c[3];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];\
"""
qc_m = QuantumCircuit.from_qasm_str(qasm)

In [9]:
qc.draw()

┌────────────┐      ┌────────────┐                                      »
q_0: ┤ RY(1.4296) ├──■───┤ RY(1.0964) ├───■──────────────────────────────────»
     ├────────────┤┌─┴─┐┌┴────────────┴┐  │                                  »
q_1: ┤ RY(2.8989) ├┤ X ├┤ RY(-0.93016) ├──┼──────────────────■───────────────»
     ├────────────┤└───┘└──────────────┘┌─┴─┐┌────────────┐┌─┴─┐┌───────────┐»
q_2: ┤ RY(1.4726) ├─────────────────────┤ X ├┤ RY(-pi/32) ├┤ X ├┤ RY(pi/32) ├»
     └────────────┘                     └───┘└────────────┘└───┘└───────────┘»
«                               
«q_0: ──■───────────────────────
«       │                       
«q_1: ──┼────────────────────■──
«     ┌─┴─┐┌──────────────┐┌─┴─┐
«q_2: ┤ X ├┤ RY(-0.29452) ├┤ X ├
«     └───┘└──────────────┘└───┘

In [4]:
job = execute(qc, BasicAer.get_backend('unitary_simulator'))
job.result().get_unitary()

array([[ 0.02917122+0.j, -0.56551617+0.j, -0.35067171+0.j,
         0.49770631+0.j, -0.01949158+0.j,  0.37786582+0.j,
         0.23431134+0.j, -0.33255673+0.j],
       [ 0.61902956+0.j,  0.34740469+0.j, -0.42932798+0.j,
         0.05596061+0.j, -0.41362233+0.j, -0.23212839+0.j,
         0.28686778+0.j, -0.03739168+0.j],
       [ 0.46102224+0.j, -0.23568516+0.j,  0.47963673+0.j,
         0.04312319+0.j, -0.46102224+0.j,  0.23568516+0.j,
        -0.47963673+0.j, -0.04312319+0.j],
       [ 0.07739211+0.j, -0.27875029+0.j, -0.17160658+0.j,
        -0.4421744 +0.j, -0.11582547+0.j,  0.41717929+0.j,
         0.25682739+0.j,  0.66176076+0.j],
       [ 0.01949158+0.j, -0.37786582+0.j, -0.23431134+0.j,
         0.33255673+0.j,  0.02917122+0.j, -0.56551617+0.j,
        -0.35067171+0.j,  0.49770631+0.j],
       [ 0.41362233+0.j,  0.23212839+0.j, -0.28686778+0.j,
         0.03739168+0.j,  0.61902956+0.j,  0.34740469+0.j,
        -0.42932798+0.j,  0.05596061+0.j],
       [ 0.46102224+0.j, -0.235685

In [5]:
job = execute(qc, BasicAer.get_backend('statevector_simulator'))
job.result().get_statevector()

array([0.02917122+0.j, 0.61902956+0.j, 0.46102224+0.j, 0.07739211+0.j,
       0.01949158+0.j, 0.41362233+0.j, 0.46102224+0.j, 0.11582547+0.j])

In [7]:
job = execute(qc_m, BasicAer.get_backend('qasm_simulator'), shots=8192)
job.result().get_counts()

{'000': 7,
 '010': 1699,
 '100': 1,
 '110': 1748,
 '111': 102,
 '001': 3241,
 '101': 1349,
 '011': 45}

In [1]:
import sys
import os
__PROJECT_ROOT__ = os.path.dirname(os.getcwd())
print("Adding project home: %s" % __PROJECT_ROOT__)
sys.path.append(__PROJECT_ROOT__)

Adding project home: /home/yue/dev/code/quantum


In [2]:
import qiskit
import numpy as np
from utils.simulator import get_unitary

qc = qiskit.QuantumCircuit(1)

qc.rx(np.pi/2, 0)
# qc.z(0)
# qc.rx(-np.pi/2, 0)

get_unitary(qc)

array([[ 7.07106781e-01+0.j        , -4.32978028e-17-0.70710678j],
       [ 4.32978028e-17-0.70710678j,  7.07106781e-01+0.j        ]])

In [13]:
from analytical.basic_gates import rx, ry, rz, pauli_x, pauli_y, pauli_z

rx(np.pi/2)*pauli_y*rx(-np.pi/2)

matrix([[ 1.+0.00000000e+00j,  0.-1.79380389e-16j],
        [-0.+1.99673462e-16j, -1.+0.00000000e+00j]])

In [12]:
rx(np.pi)*pauli_y

matrix([[ 1.+0.000000e+00j,  0.-6.123234e-17j],
        [ 0.+6.123234e-17j, -1.+0.000000e+00j]])